import { createElement } from "lwc";
import ExternalActionLogger from "pi_ea_utils/externalActionLogger";

describe("pi_ea_utils-external-action-logger", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("pi_ea_utils-external-action-logger", {
      is: ExternalActionLogger
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
